name: word_chain_battle
description: A Korean word chain battle game with AI challenges
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 상태 관리
  provider: ^6.0.5
  
  # HTTP 클라이언트
  dio: ^5.3.2
  
  # 라우팅
  go_router: ^10.0.0
  
  # 로컬 저장소
  shared_preferences: ^2.2.2
  
  # 애니메이션
  flutter_animate: ^4.2.0
  
  # 폰트
  google_fonts: ^6.1.0
  
  # 유틸리티
  flutter_screenutil: ^5.8.4
  
  # 사운드 재생
  audioplayers: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/backgrounds/
    - assets/images/ui/
    - assets/fonts/
    - assets/data/
    - assets/sounds/
  
  # fonts:
  #   - family: GameFont
  #     fonts:
  #       - asset: assets/fonts/game_font.ttf
