name: word_chain_backend
description: Backend server for Word Chain Battle game
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # 웹 서버 프레임워크
  alfred: ^5.0.0
  
  # HTTP 클라이언트
  dio: ^5.3.2
  
  # JSON 처리
  json_annotation: ^4.8.1
  
  # 데이터베이스
  sqlite3: ^2.1.0
  
  # 유틸리티
  uuid: ^4.0.0
  
  # 로깅
  logging: ^1.2.0

dev_dependencies:
  # 코드 생성
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  
  # 테스트
  test: ^1.24.0
