name: word_chain_backend
description: Backend server for Word Chain Battle game
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # 웹 서버 프레임워크
  alfred: ^1.1.3
  
  # 데이터베이스
  sqflite_common_ffi: ^2.3.0+1
  path: ^1.8.3
  
  # JSON 처리
  json_annotation: ^4.8.1
  
  # HTTP 통신
  http: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
